name: Deploy on S3

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy on S3
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

    - name: Check out code
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Create env file
      run: |
        touch .env
        echo REACT_APP_SERVER_URL=${{ secrets.CRA_URL }} >> .env
        cat .env

    - name: Install dependencies
      run: npm i

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor

    - name: Run test with coverage
      run: npm run lint:cov

    - name: Run test with coverage
      run: npm run test:cov

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_RUN_PROJECT_KEY: ${{ secrets.SONAR_RUN_PROJECT_KEY }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync S3
      run: aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read

    - name: Invalidate Cloudfront
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DIST_ID }} --paths "/*" --no-cli-pager

  k6:
    name: K6 test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run XK6 Browser
        uses: grafana/xk6-browser-github-action@v1
        with:
          include: k6/frontend.js
          args: -e BASE_URL=${{ secrets.ADORA_FRONTEND }}
